name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'trackx-demo'
      - uses: actions/checkout@v3
        with:
          repository: 'maxmilton/trackx'
          path: 'trackx'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install --global pnpm
      - run: pnpm --dir trackx install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm --dir trackx-demo install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm --dir trackx-demo run setup # includes build
      - run: pnpm --dir trackx-demo run test
      - name: Report coverage
        run: |
          cd trackx-demo
          curl -Lo ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'trackx-demo'
      - uses: actions/checkout@v3
        with:
          repository: 'maxmilton/trackx'
          path: 'trackx'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install --global pnpm
      - run: pnpm --dir trackx install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm --dir trackx-demo install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm --dir trackx-demo run lint
