name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'trackx-demo'
      - uses: actions/checkout@v2
        with:
          repository: 'maxmilton/trackx'
          path: 'trackx'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm --dir trackx install --frozen-lockfile
      - run: pnpm --dir trackx run setup # includes build
      - run: pnpm --dir trackx run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'trackx-demo'
      - uses: actions/checkout@v2
        with:
          repository: 'maxmilton/trackx'
          path: 'trackx'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm --dir trackx install --frozen-lockfile
      - run: pnpm --dir trackx run lint
