name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'maxmilton/trackx'
          path: '../trackx'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
      # - run: pnpm run build
      - run: pnpm run setup
      - run: pnpm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'maxmilton/trackx'
          path: '../trackx'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
